test(platform): assemble_space : begin test Publish
add useState to service;

note:
test Modal snapshot error: parentInstance.children.indexOf is not a function

refer to:
https://github.com/reactjs/react-modal/issues/553
https://medium.com/@amanverma.dev/mocking-create-portal-to-utilize-react-test-renderer-in-writing-snapshot-uts-c49773c88acd

this is react-test-renderer's bug that the Modal use createPortal and cause the error!
so not test Modal snapshot!